# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    # Configuración de Assets (importante para que uploads funcione)
    assets:
        base_path: '/'
        packages:
            # Esto permite servir directamente la carpeta uploads sin que AssetMapper la interfiera
            uploads:
                base_path: '/uploads'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
